#%RAML 1.0
title: Market
version: v1
baseUri: http://localhost:8081

uses:
  OrderLibrary: OrderLibrary.raml

types:
  orderRequest:
    type: object
    properties:
      partNumber: string
      budget: string


/getBestOffer:
  post:
    description: Determines the cheapest offer and makes an order. The cheapest material should be ordered as often as the budget allows.
    body:
      application/json:
        type: orderRequest
        example: { "partNumber": "TRFR2004", "budget": "2000" }

    responses:
      200:
        body:
          application/json:
            type: OrderLibrary.Order
            example: { "number": "TRFR2022", "description": "Touringrahmen-Silber", "price": 14.91, "currency" : EUR, "suppliernumber": "000012100", "quantity": 67}
