#%RAML 1.0
title: Market
version: v1
baseUri: http://localhost:3000

uses:
  OrderLibrary: OrderLibrary.raml

types:
  test:
    type: object
    properties:
      partNumber: string
      budget: number


/getBestOffer:
  post:
    description: Determines the cheapest offer and makes an order. The cheapest material should be ordered as often as the budget allows.
    body:
      application/json:
        type: test
        example: { "partNumber": "TRFR2022", "budget": 25.20 }

    responses:
      200:
        body:
          application/json:
            type: OrderLibrary.Order
            example: { "partNumber": "TRFR2022", "description": "Touringrahmen-Silber", "price": "14.91", "currency" : EUR, "suppliernumber": "000012100", "quantity": 67}
