#%RAML 1.0 Library
types:
  Order:
    type: Material
    properties:
      suppliernumber: string
      quantity: integer
  Material:
    type: object
    properties:
      partNumber: string
      description?: string
      price: number
      currency: string

